noncelab/coconut_wallet

lib/screens/faucet_request_screen.dart

TextField 입력된 문자열의 중간으로 커서 이동 후에 문자를 입력하면 커서가 문자열의 끝으로 이동하는 현상
[테스트 비트코인 받기] - 받을 주소

#3 TextField 입력된 문자열에서 중간 문자 변경 시 커서가 이동됨

---

android/app/src/main/kotlin/onl/coconut/wallet/MainActivity.kt
lib/main.dart
lib/widgets/qrcode_info.dart

- 기기가 안드로이드 8.0일 경우에는 앱 실행시 SystemChrome.setPreferredOrientations 함수 실행하지 않습니다.
-deviceInfo 패키지를 통해 platformVersion을 확인하는 과정에서, 일부 버전에서는 '8.0.0' 형식으로 반환 하여 Integer를 Parse 하는 과정에서 충돌이 발생하였습니다. platformVersion이 아닌 sdkVersion을 통해 Integer 형식으로 가져오도록 하고, 네이티브 MethodChannel을 통해  버전을 가져오도록 변경했습니다.

issue #15 fix(android8.0): 기기가 안드로이드 8.0일 경우 분기 처리

---

lib/providers/view_model/wallet_detail/wallet_detail_view_model.dart
lib/screens/wallet_detail/wallet_detail_screen.dart
lib/services/dio_client.dart
lib/services/faucet_service.dart
lib/widgets/overlays/faucet_request_bottom_sheet.dart

- 수도꼭지 서버 상태 조회: wallet_detail 화면 진입 시 상태 조회 하던 것을 -> 수도꼭지 바텀시트의 initState로 옮김
- 아래 상황을 '단수 상태'로 안내하는 ui 추가
1) 수도꼭지 서버 상태 조회 시 에러 발생
2) 수도꼭지 서버 응답이 정상이지만 요청 수량이 0인 경우
related to Issue #97

[13-979] fix(faucet-status): 수도꼭지 상태 조회 타이밍 변경

---

lib/providers/app_sub_state_model.dart
lib/providers/view_model/send/send_fee_selection_view_model.dart
lib/providers/view_model/wallet_detail/wallet_detail_view_model.dart
lib/screens/wallet_detail/wallet_detail_screen.dart
lib/widgets/selector/wallet_detail_tab.dart

- wallet_detail_screen.dart 업데이트 실패 상태 텍스트 추가
- 업데이트 실패 상태일 때 '받기', '보내기' 버튼 차단 
- '화면을 아래로 당겨 최신 데이터를 가져와 주세요.' 토스트 추가

[13-980/982] utxo 목록 조회에 실패했을 때,  walletStatus 정의 안됐을 때 에러 처리

---

lib/providers/transaction_provider.dart
lib/providers/view_model/wallet_detail/transaction_detail_view_model.dart
lib/providers/view_model/wallet_detail/utxo_detail_view_model.dart
lib/screens/wallet_detail/transaction_detail_screen.dart
lib/screens/wallet_detail/wallet_detail_screen.dart
lib/utils/transaction_util.dart

Issue #99 
TransactionProvider에 뷰 관련 로직 뷰 모델로 분리
- TransactionProvider에서 제거할 변수 및 함수: 화면에 표시할 input/output 갯수, 더보기 버튼, 더보기 버튼 클릭 시 호출 함수
- 이동 대상 뷰 모델: TransactionDetailViewModel, UtxoDetailViewModel
- 두 뷰 모델에서 Input/Output 요소를 보여주기 위해 필요한 공통 함수를 TransactionUtil에 추가

[13-999] refactoring tx provider 

---

lib/providers/view_model/send/send_amount_view_model.dart
lib/providers/view_model/send/send_confirm_view_model.dart
lib/providers/view_model/send/send_fee_selection_view_model.dart
lib/providers/view_model/send/send_utxo_selection_view_model.dart
lib/screens/send/send_amount_screen.dart

- send_amount_view_model
- unspent 상태의 utxo 총합만큼만 보낼 수 있음
- 화면에 머무르는 동안 Utxo 목록이 변하는 경우 최대 전송 금액이 달라져야 하기 때문에 _walletProvider에 이벤트 등록/해제 로직을 추가
- send_fee_selection_view_model
- confirmedBalance 계산로직 변경 - unspent 상태의 utxo 총합
- send_utxo_selection_view_model
- confirmedBalance 계산로직 변경 - unspent 상태의 utxo 총합
- _createTransaction 함수에서 할당 안된 satsPerVb와 _sendInfoProvider.feeRate을 할당하는 코드가 있어서 수정

[14-1069] Fix/send amount

---

lib/enums/network_enums.dart
lib/enums/utxo_enums.dart
lib/model/utxo/utxo_state.dart
lib/model/wallet/transaction_record.dart
lib/providers/node_provider/transaction/rbf_handler.dart
lib/providers/node_provider/transaction/transaction_fetcher.dart
lib/providers/node_provider/transaction/transaction_processor.dart
lib/providers/transaction_provider.dart
lib/providers/view_model/send/broadcasting_view_model.dart
lib/providers/view_model/send/send_utxo_selection_view_model.dart
lib/providers/view_model/wallet_detail/fee_bumping_view_model.dart
lib/providers/view_model/wallet_detail/transaction_detail_view_model.dart
lib/providers/view_model/wallet_detail/utxo_detail_view_model.dart
lib/providers/view_model/wallet_detail/utxo_list_view_model.dart
lib/providers/view_model/wallet_detail/wallet_detail_view_model.dart
lib/repository/realm/converter/transaction.dart
lib/repository/realm/migration/migrator_ver2_1_0.dart
lib/repository/realm/model/coconut_wallet_model.dart
lib/repository/realm/model/coconut_wallet_model.realm.dart
lib/repository/realm/transaction_repository.dart
lib/screens/wallet_detail/transaction_detail_screen.dart
lib/screens/wallet_detail/transaction_fee_bumping_screen.dart
lib/utils/transaction_util.dart
lib/widgets/card/transaction_item_card.dart
test/mock/transaction_mock.dart
test/providers/node_provider/transaction_manager_test.dart

- vSize 값이 int라서 정확한 feeRate을 계산하기 어려운 문제 수정
- 로직 상 non-null이 보장 가능한 프로퍼티들 중에서 nullable로 사용된 프로퍼티 수정
- transactionType Enum값을 사용하고 Realm에 저장할 때만 String으로 저장하도록 수정
- Realm
- 위에서 수정된 타입 대응
- WalletBase에 안쓰는 프로퍼티 삭제

[14-1088] TransactionRecord 프로퍼티 수정

---

lib/constants/network_constants.dart
lib/model/node/wallet_update_info.dart
lib/providers/node_provider/balance_manager.dart
lib/providers/node_provider/isolate/isolate_manager.dart
lib/providers/node_provider/isolate/isolate_state_manager.dart
lib/providers/node_provider/state_manager.dart
lib/providers/node_provider/subscription/script_callback_manager.dart
lib/providers/node_provider/subscription/script_event_handler.dart
lib/providers/node_provider/subscription/script_handler_util.dart
lib/providers/node_provider/subscription/script_subscriber.dart
lib/providers/node_provider/subscription/transaction_processing_state.dart
lib/providers/node_provider/subscription_manager.dart
lib/providers/node_provider/transaction/rbf_handler.dart
lib/providers/node_provider/transaction/transaction_fetcher.dart
lib/providers/node_provider/transaction/transaction_manager.dart
lib/providers/node_provider/transaction/transaction_processor.dart
lib/providers/node_provider/utxo_manager.dart
lib/providers/view_model/wallet_detail/utxo_list_view_model.dart
lib/providers/wallet_provider.dart
lib/repository/realm/subscription_repository.dart
lib/repository/realm/transaction_repository.dart
lib/screens/home/wallet_list_screen.dart

- 이벤트 핸들러가 동시에 같은 트랜잭션을 fetching 하지 않도록 방지
- state 변경 시 임의로 notifyListeners 지연해서 호출하던 코드 삭제
- isolate 에서 state 제어하는 로직에 카운터 추가 
1. 지갑 리스트, 지갑 상세 화면에서 트랜잭션 발생시키기
2. 잔액이 정상적으로 수정되는지 확인
1. 여러개의 UTXO를 생성하거나 소비하는 등 이벤트 핸들러가 여러개 동작하게 하는 트랜잭션 발생
2. 로그에 아래 로그가 트랜잭션마다 1개씩 출력되는지 확인
```log
-------- fetchScriptTransaction에서 처리중인 트랜잭션: <TX_HASH>
```
- utxo 목록은 간헐적으로 갱신이 안되는 현상이 있으나 166번 이슈 머지된 후 다시 수정할 예정입니다.
#164

[164] 네트워크 동시성 오류 수정

---

lib/screens/home/wallet_add_input_screen.dart

- 키보드가 올라온 상태에서 '지갑 추가 정보'를 확인할 수 있도록 수정(margin 추가)
(lib/screens/home/wallet_add_input_screen.dart)
1. 앱 실행 후 지갑 추가 - 직접 입력 페이지 이동하여 확인
1. 화면 진입 직후 Text Field 터치 시 포커스가 되지 않는 문제가 있습니다. (불규칙적으로 발생)
=> CoconutTextInput에서 placeholder Text를 클릭한 경우 포커스가 되지 않는 이슈가 있어 CDS에서 수정될 예정입니다(피오)
2. 포커스 된 상태에서 가이드를 펼쳤을 때 안내 사항이 키보드 위 버튼에 가려져 보이지 않습니다.
=> 수정 완료 
#186

[186] Bug - wallet_add_input_screen UI

---

lib/repository/realm/wallet_repository.dart

- 단일서명지갑 삭제시 연결된 외부지갑 스키마가 있는 경우에만 삭제
(lib/repository/realm/wallet_repository.dart)
1. 코코넛 지갑 추가 이후 정상적으로 삭제가 되는지 확인
#196

[196] Bug - 월렛 삭제시 없는 스키마를 참조하는 문제

---

lib/screens/home/wallet_add_scanner_screen.dart
lib/screens/wallet_detail/wallet_info_edit_bottom_sheet.dart
lib/screens/wallet_detail/wallet_info_screen.dart
pubspec.yaml

외부지갑이름 수정 화면
- 바텀시트를 열었을 때 키보드도 함께 올라오도록 수정
- 앱바 영역에서 leadingIcon 패딩을 vertical,horizontal 동일하게 설정
스캔화면 다이얼로그
- CustomDialogs -> CoconutPopup으로 교체
- 다이얼로그 모서리 부분에 일부가 비치는 현상 해결
CDS branch: fix/appbar-height-dialog-padding 머지 된 후 pubspec에 CDS 브랜치 main으로 변경
<table>
<tr>
<div align="center">
src="https://github.com/user-attachments/assets/335496b0-511e-4925-88bd-951263bc6c90"
width="300"
>
src="https://github.com/user-attachments/assets/d9a08cb7-d950-4a80-837a-77bc1bdb181d"
width="300"
>
</div>
</tr>
<tr>
<div align="center">
src="https://github.com/user-attachments/assets/f15e012b-a56c-404c-b673-6090d7ba7d7a"
width="300"
>
src="https://github.com/user-attachments/assets/79f8e144-1756-4d2f-a59b-df0981b86d65"
width="300"
>
</div>
</tr>
</table>
#180

[194] 지갑 추가 및 정보 화면 UI 수정

---

assets/i18n/kr.i18n.yaml
lib/app.dart
lib/app_guard.dart
lib/constants/network_constants.dart
lib/providers/node_provider/isolate/isolate_manager.dart
lib/providers/node_provider/node_provider.dart
lib/screens/send/send_fee_selection_screen.dart
lib/screens/wallet_detail/transaction_fee_bumping_screen.dart
lib/services/network/socket/socket_manager.dart
lib/widgets/overlays/coconut_loading_overlay.dart
pubspec.yaml

- (+) 클릭 불가능한 배경 + CoconutCircularIndicator 조합인 CoconutLoadingOverlay 위젯 구현
- (+) 보내기 - 수수료 입력 화면, FeeBumping-수수료 입력 화면: context.loaderOverlay.show / hide 대신 CoconutLoadingOverlay를 visible/invisible 처리
[WalletList-외부지갑카드 확인]
- sendFeeSelectionScreen, transactionFeeBumpingScreen에서 _isLoaing = false 모두 주석처리 후 해당 화면 진입
<table>
<tr>
<div align="center">
src="https://github.com/user-attachments/assets/d6595e43-af34-43a0-ad80-bbf49d503653"
width="300"
>
</div>
</tr>
</table>
#174

[174] 수수료 조회 화면에서 로딩이 계속되며 뒤로가기가 안됨

---

lib/screens/wallet_detail/utxo_detail_screen.dart
lib/screens/wallet_detail/utxo_list_screen.dart
lib/screens/wallet_detail/wallet_detail_screen.dart
lib/widgets/dropdown/utxo_filter_dropdown.dart
lib/widgets/header/utxo_list_header.dart
lib/widgets/header/utxo_list_sticky_header.dart

[utxo_list_screen]
- (기존) Consumer 사용 → (개선) Selector 사용
- sticky header/header, dropdown menu 표시
- (기존) setState를 통해 상태 변경 → (개선) ValueNotifier 사용
- sticky header와 기본 header의 dropdodwn menu를 표시하기 위해 각각 나뉘어져 있던 변수 통합
[wallet_detail_screen]
- utxo_list와 동일하게 동작하도록 수정
- sticky header/header
- (기존) setState를 통해 상태 변경 → (개선) ValueNotifier 사용
#206

[206] Tx, Utxo 목록 화면 리팩터링

---

assets/i18n/kr.i18n.yaml
lib/providers/view_model/home/wallet_add_input_view_model.dart
lib/screens/home/wallet_add_input_screen.dart
lib/utils/descriptor_util.dart
lib/widgets/card/wallet_item_card.dart
test/utils/descriptor_util_test.dart

- 체크섬 유무를 검사할 때 regex를 사용하지 않고 '#' 문자 여부로 판단(이후 로직은 라이브러리에 맡김)
- 공백 문자열 trim 처리
- 입력 가능한 문자가 아닌 경우 에러메시지 처리(허용하지 않는 문자가 있어요)
vpub5YSvHLYgfaDn1HFBxmnk2i23UFpNBLNJNFGfkdbEtwijtwHHMv5UhH6QATGasJWmRp8TPJfxysxdQxRZ8CQqtu54vXBRz696bSraBPThxNg
wpkh([F75F5AB5/84'/1'/0']vpub5YSvHLYgfaDn1HFBxmnk2i23UFpNBLNJNFGfkdbEtwijtwHHMv5UhH6QATGasJWmRp8TPJfxysxdQxRZ8CQqtu54vXBRz696bSraBPThxNg/<0;1>/*)#k8xga4tv
[F75F5AB5/84'/1'/0']vpub5YSvHLYgfaDn1HFBxmnk2i23UFpNBLNJNFGfkdbEtwijtwHHMv5UhH6QATGasJWmRp8TPJfxysxdQxRZ8CQqtu54vXBRz696bSraBPThxNg
1. 직접 입력시 공백 문자열 trim 확인, 허용되지 않은 문자에 대한 에러메시지 확인
#198 #204

[198/204] 직접 입력 시 포맷 및 네트워크 검사

---

lib/providers/view_model/wallet_detail/wallet_info_edit_view_model.dart
lib/screens/wallet_detail/wallet_info_edit_bottom_sheet.dart

- 구조 변경: addListener를 initState에서 호출함
- Consumer 대신 Selector 사용
- 개선: Focus out 시 build 함수 호출 횟수: 20회 → 2회
- https://github.com/noncelab/coconut_wallet/pull/194#discussion_r2062807725
#206

[206] 타사 지갑 이름 변경 리팩터링

---

assets/i18n/kr.i18n.yaml
integration_test/wallet_add_test.dart
lib/providers/view_model/home/wallet_add_input_view_model.dart
lib/screens/home/wallet_add_input_screen.dart
lib/screens/home/wallet_add_mfp_input_bottom_sheet.dart
lib/services/wallet_add_service.dart

- 확장공개키를 통한 지갑추가시 mfp를 추가로 입력받도록 처리
- 지갑추가 로딩중에 텍스트 입력 막도록 수정
(lib/screens/home/wallet_add_input_screen.dart)
- 마스터 핑크프린트 입력 바텀시트 추가
(lib/screens/home/wallet_add_mfp_input_bottom_sheet.dart)
1. 지갑추가 - 직접 입력 - 디스크립터/확장공개키 입력
TC1: 디스크립터 입력후 완료 버튼 클릭, 지갑 추가 
TC2: 확장공개키 입력후 완료 버튼 클릭, MFP 바텀시트가 나온다. 
- 건너뛰기 클릭시 지갑이 추가된다(지갑정보 확인시 MFP '-')
- MFP 입력후 완료 버튼 클릭시 지갑이 추가된다(지갑정보 MFP 확인)
#209 #213

[209/213] 확장공개키로 추가하는 경우, MFP 입력 허용하기

---

assets/i18n/kr.i18n.yaml
lib/screens/common/tag_bottom_sheet.dart
lib/screens/wallet_detail/utxo_detail_screen.dart
lib/utils/colors_util.dart
lib/widgets/card/selectable_utxo_item_card.dart
lib/widgets/card/utxo_item_card.dart
lib/widgets/card/wallet_list_glossary_shortcut_card.dart

- 태그 colorIndex가 gray일때 화면에 표시되는 borderColor,textColor 수정(gray600 -> gray400)
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/3660545a-8c5c-4f8f-b177-bf9b8a40b7af" width="300"/></td>
<td><img src="https://github.com/user-attachments/assets/5bc976f0-d0cc-4cb4-a454-8f79e4e63bdb" width="300"/></td>
<td><img src="https://github.com/user-attachments/assets/0aed2519-c5f5-4396-b868-d888b9ec33ae" width="300"/></td>
<td><img src="https://github.com/user-attachments/assets/8cd6e2dd-1bae-4b20-a66e-26fea8eebaf7" width="300"/></td>
</tr>
</table>
<br>
- 잔돈 툴팁 문구 변경
<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/59afc0fb-31d6-4c8a-9717-a0a8a76d6c80" width="300"/></td>
</tr>
</table>
<br>
- 숏컷 문구 미트볼 -> 케밥 아이콘으로 변경
<table>
<tr>
<td><img …

[UI] 태그 색상(gray), '잔돈'툴팁, 숏컷 케밥 아이콘

---

integration_test/README.md
integration_test/integration_test_utils.dart
integration_test/realm_migration_test.dart
lib/constants/realm_constants.dart
lib/repository/realm/migration/migration.dart
lib/repository/realm/model/coconut_wallet_model.dart
lib/repository/realm/realm_manager.dart
lib/repository/realm/transaction_repository.dart
test/repository/realm/realm_migration_test.dart
test/repository/realm/transaction_repository_test.dart

- isLatestTxBlockHeightZero 삭제 테스트 코드 추가(유닛, 통합 테스트)
(test/repository/realm/realm_migration_test.dart, integration_test/realm_migration_test.dart)
- WalletBase isLatestTxBlockHeightZero 삭제
(lib/repository/realm/model/coconut_wallet_model.dart)
- Realm 스키마 버전 변경(2 -> 3) 및 마이그레이션 함수 변경(removeIsLatestTxBlockHeightZero)
(lib/repository/realm/migration/migration.dart, lib/repository/realm/realm_manager.dart)
1. 유닛 테스트 명령어
flutter test test/repository/realm/realm_migration_test.dart
2. 통합 테스트 명령어
flutter test --plain-name "[Migration X] [Wallet O]" --flavor regtest integration_test/realm_migration_test.dart &&
flutter test --plain-name "[Migration X] [Wallet X]" --flavor regtest integration_test/realm_migration_test.dart &&
flutter test --plain-name "[0 -> kRealmVersion] [Wallet O]" --flavor …

[182] _RealmWalletBase 미사용 프로퍼티 삭제

---

lib/screens/home/wallet_add_scanner_screen.dart

feat(wallet_add_scanner_screen): qr 지갑추가 실패시 에러메시지 처리(기본 문구, 네트워크가 다른 경우)
1. 지갑추가 - 키스톤 - QR 코드 스캔하여 테스트
1. 비트코인 네트워크를 지원하지 않는 월렛 추가(메타마스크) - '확인할 수 없는 형식이에요' 문구 확인
2. 메인넷 지갑 추가(넌척) - '테스트넷 지갑이 아니에요' 문구 확인
3. 테스트넷 지갑 추가(스패로우) - 정상 추가 확인
https://github.com/user-attachments/assets/364b6ada-fbde-4a25-a70c-2c1a38e8ad47  
https://github.com/user-attachments/assets/de7dbcd8-1e6f-4149-8cb1-c8f63546b772
#218

[218] 지갑 추가 - 다른 네트워크의 QR 스캔 시 에러메시지 개선

---

lib/providers/view_model/home/wallet_add_input_view_model.dart
lib/screens/home/wallet_add_input_screen.dart
lib/utils/descriptor_util.dart
test/utils/descriptor_util_test.dart

fix(wallet_add_input_view_model): 네트워크에 따른 주소가 틀린 경우, 지갑 에러메시지를 표시하도록 수정
feat(descriptor_util_test): 네트워크에 따른 주소에 대한 테스트에서 에러메시지를 검증하도록 수정
1. 명령어를 통한 유닛테스트 코드 실행
flutter test test/utils/descriptor_util_test.dart
2. 지갑추가 - 직접 입력 페이지에서 직접 테스트
- 테스트 코드: NetworkType에 따른 주소가 맞는지 검증 부분 참고 
#219

[219] 지갑추가 - 직접 입력 에러메시지 불일치

---

lib/providers/node_provider/transaction/transaction_sync_service.dart
test/providers/node_provider/transaction_sync_service_test.dart

- 멤풀에 트랜잭션이 대체되었는지 확인하는 방법 변경
- 기존: electrum api 에서 verbose 옵션으로 상세 정보를 조회할 수 있으면 멤풀에 존재하는 트랜잭션으로 간주
- 개선: 트랜잭션의 인풋이 겹치는지, 수수료율이 증가했는지 확인
- RBF 시도 후 Utxo 목록, Tx 내역이 정상적으로 존재하는지 확인
- #243

fix(replaced-tx): 대체된 트랜잭션 판단 기준에 FeeRate 비교 로직 추가

---

lib/providers/view_model/wallet_detail/fee_bumping_view_model.dart

rbf/cpfp 과정에서 walletImportSource 설정 누락으로 
signed_psbt_scanner 화면의 initState 과정에서 발생하는 오류를 해결했습니다.
(rbf 테스트 완료했습니다.)
issue #246

fix(walletImportSource): rbf/cpfp 과정에서 값 설정 누락

---

lib/providers/view_model/wallet_detail/transaction_detail_view_model.dart
lib/screens/wallet_detail/transaction_detail_screen.dart
lib/screens/wallet_detail/wallet_detail_screen.dart

- MFP가 지정되지 않은 지갑은 fee bumping 화면으로 이동할 수 없도록 버튼 스타일에 opacity를 적용함.
- wallet_detail_screen에서 토스트를 띄워주기 때문에 위와 같이 조치함

fix(btn-disabled): MFP가 지정되지 않은 지갑은 fee bumping 화면으로 이동할 수 없음

---

lib/repository/realm/migration/migration.dart

테스트 방법 
1. 앱 삭제 
2. $ flutter pub run build_runner clean && flutter pub run build_runner build --delete-conflicting-outputs && dart run realm generate
3. develop 브랜치에서 앱 설치 
4. 지갑 추가 
5. 브랜치를 fix/245-migration으로 변경
6. $ flutter pub run build_runner clean && flutter pub run build_runner build --delete-conflicting-outputs && dart run
7. 앱 실행
migration error 안나는지 확인

fix(migration): _RealmUtxo isDeleted 추가

---

lib/providers/node_provider/node_provider.dart
lib/providers/wallet_provider.dart

- 화면 이탈 후 NodeProvider 이벤트 리스너에 의해 재구독을 시도하지 않도록 수정
- 화면 이탈 ➡️ 다시 복귀 ➡️ 이벤트 발생시키기 (트랜잭션 보내기/받기 모두 상관 없음)
- #248

 [#248] 앱 이탈 - 복귀 - 트랜잭션 발생 시 지갑 구독해제/구독 함수 수차례 호출

---

lib/services/speed_app_ln_invoice_service.dart
test/services/speed_app_ln_invoice_service_test.dart

feat(ln_invoice_service): 라이트닝 인보이스 주소 생성 로직, 테스트 코드 추가
1. 명령어를 통한 유닛테스트 코드 실행
flutter test  test/services/speed_app_ln_invoice_service_test.dart
1. 정상적인 범위의 amount를 입력한 경우, 라이트닝 인보이스 주소가 제대로 생성된다.
2. 비정상적 범위의 amount를 입력한 경우, 오류가 발생한다.
#258

[258] 스피드앱 라이트닝 인보이스 생성

---

lib/widgets/card/address_and_amount_card.dart

fix(address_and_amount_card): 수량 필드 스크롤 되지 않도록 수정
1. 앱 실행하여 확인
1. 앱 실행 -> 지갑 선택 -> 보내기 버튼 클릭 -> 상단 오른쪽 여러 주소로 보내기 클릭
2. 받는 사람 카드에서 주소 필드는 '여러 줄', 수량 필드는 '1줄'로 입력되는지 확인(두 경우 모두 스크롤 불가) 
#267

[267] 배치 트랜잭션 수량 입력 필드 스크롤 가능

---

lib/screens/home/wallet_add_input_screen.dart
lib/screens/home/wallet_add_mfp_input_bottom_sheet.dart
lib/utils/descriptor_util.dart
test/utils/descriptor_util_test.dart

1. `descriptor_util.dart`
- extractPurpose, validatePurpose 수정(hardened 표기 `'`, `h` 모두 허용) 
2. 직접 입력 화면 bottom sheet 동작 수정
- ex pub 입력 케이스에서, [완료] 버튼 눌러 mfp 입력 화면으로 전환 시, bottom sheet focus 및 키보드 열림 동작 수정
(변경 전: 키보드가 닫히고 다시 열리면서, bottomSheet가 키보드의 아래로 내려갔다가 올라오는 동작이 보기 불편함)
- bottomSheet의 버튼을 눌러 지갑을 추가할 때 키보드가 닫히도록 수정 
(변경 전: _closeKeyboard() 함수를 호출하고 있으나, 실제로 bottomSheet 내부에서 focusNode 변수를 사용하고 있어서 동작하지 않음. 키보드가 열려있는 채로 로딩 인디케이터 노출)
3. 도움말 제목 폰트 사이즈 12 > 14
1. 직접 입력 화면 도움말 넌척 케이스대로, Keys 탭에서 Key spec 정보로 추가 시도
- 지갑 추가 로딩 인디케이터 노출 시 키보드 닫히는지 확인
2. 확장 공개키 입력
- mfp 입력 화면으로 이동 시 동작 확인
- 건너뛰기 / 완료 버튼 클릭 시 키보드 닫힘 확인

fix(wallet-add-screen): 버그 수정 및 ui 수정

---

lib/providers/wallet_provider.dart

wallet_provider의 _findSameWalletIndex 함수를 수정
원래는 descriptor를 직접 비교하거나 parentFingerprint를 비교했지만,
첫번째 Receive 주소를 비교하여 중복 체크하도록 변경
이유는 키스톤의 descriptor 안에 포함된 확장공개키가 비표준이어서 
다른 지갑들과 형태가 다르기 때문입니다.
메인넷 버전으로 실행한 뒤, 
관련 mattermost 스레드에 공유된 지갑 추가 소스들로 지갑을 추가해 보고, 
단 1개만 추가되는지 확인합니다. 
3. 이슈번호
#285

[#285] 키스톤 지갑 때문에 중복 지갑 찾기 실패

---

lib/utils/descriptor_util.dart
test/utils/descriptor_util_test.dart

- 디스크립터 regex 리팩토링
Pororo님 버그 제보: account 0이 아닌 path가 포함된 경우 '확인할 수 없는 형식이에요'

fix(account-in-path): 0이 아닌 account 허용하도록 수정

---

lib/providers/node_provider/transaction/transaction_record_service.dart

- OP_RETURN 트랜잭션의 경우 트랜잭션 상세에 주소 표기 안되도록 수정
- 저에게 OP_RETURN을 받을 주소를 알려주시면 트랜잭션 만들어드립니다.
- 멤풀 사이트에 OP_RETURN 조회된 것을 확인하고 지갑 앱에서는 표기 안되는 것을 같이 확인
- #302

[302] OP_RETURN 트랜잭션 표기 수정

---

assets/i18n/kr.i18n.yaml
lib/model/send/fee_info.dart
lib/providers/view_model/send/send_fee_selection_view_model.dart
lib/providers/view_model/send/send_utxo_selection_view_model.dart
lib/providers/view_model/wallet_detail/fee_bumping_view_model.dart
lib/screens/common/text_field_bottom_sheet.dart
lib/screens/send/fee_selection_screen.dart
lib/screens/send/send_fee_selection_screen.dart
lib/screens/send/send_utxo_selection_screen.dart
lib/screens/wallet_detail/transaction_fee_bumping_screen.dart
lib/services/model/response/recommended_fee.dart
lib/utils/transaction_util.dart
lib/widgets/card/send_fee_selection_item_card.dart
lib/widgets/textfield/custom_limit_text_field.dart

1) 보내기 과정에서 수수료 설정 화면 - 직접 입력
2) 보내기 과정에서 UTXO 선택 전송 화면 - 수수료 변경 - 직접 입력
1) 소수점 2자리까지만 입력되도록 입력값 제어
2) 최대 10자리까지만 입력되도록 입력값 제어
3) 소숫점으로 입력된 수수료율로 예상 수수료 계산
4) 직접 입력 TextField placeholder 변경
1) 1-1에 명시한 화면에서 입력값 제어가 제대로 되고, 입력 값으로 예상 수수료 계산/설정이 잘 되는지 확인
#294

[294] 수수료율 소수점 2자리까지 직접 입력 가능

---

lib/widgets/overlays/common_bottom_sheets.dart

DraggableScrollableSheet의 minChildSize 수정
1) 용어집 - 상세 설명 화면
DraggableScrollableSheet에서 snap이 true면 드래그하다가 손을 떼면 가까운 snap 위치로 자동 이동합니다.
만약 minChildSize가 maxHeight 이하면, 손을 뗐을 때 최소 크기로 유지될 수 있습니다.
minChildSize
- DraggableScrollableSheet의 높이를 비율(0.0 ~ 1.0) 로 지정합니다.
maxHeight
- showModalBottomSheet의 constraints에서 사용하는 값이며, 실제 최대 높이 제한입니다.
minChildSize 값을 maxHeight(0.9) 보다 크게 설정하여 일정량의 스크롤을 하고 손을 떼어도 maxHeight값으로 고정되지 않고 완전히 닫히도록 개선했습니다.
#308

[308] 용어설명 화면의 DraggableScrollableSheet 닫힘 중단 현상

---

lib/providers/view_model/send/send_address_view_model.dart
lib/screens/send/send_address_screen.dart

<table>
<tr>
<td>
</td>
</tr>
</table>
1) 보내기 - 주소 스캔 화면
1) 라이프사이클 변경될 때 마다 클립보드에서 복사된 내용 가져오도록 개선
2) 메서드명 변경: loadDataFromClipboardIfValid -> loadDataFromClipboard
1) 클립보드에 주소 복사를 하지 않은 상태에서 보내기 - 주소 스캔 화면에 진입합니다.
2) 백그라운드로 전환해 정상적인 주소를 복사합니다.
3) 다시 앱의 포그라운드로 들어와 '붙여넣기'버튼이 활성화 되는지 확인합니다.
#313

[313] 주소 스캔 화면 - 포그라운드로 복귀 시 붙여넣기 활성화 되도록 개선

---

ios/Runner/Base.lproj/LaunchScreen.storyboard
ios/Runner/Base.lproj/LaunchScreenRegtest.storyboard
lib/screens/onboarding/start_screen.dart

- start_screen.dart 아이콘 사이즈 지정
- iOS LaunchScreen 아이콘 사이즈 지정
1. 어플 실행하여 스플래시 아이콘 확인
[iPhone 11]
https://github.com/user-attachments/assets/7c3812a5-026b-422a-92a3-14e73a610419
[iPhone SE 2nd Generation]
https://github.com/user-attachments/assets/11d0f948-995c-4914-bbd6-b1c61a8e38a1
[SM A235N]
https://github.com/user-attachments/assets/07f18bfe-1ed5-493d-a294-50c3e9b429b8
#279

[279] StartScreen 로고 사이즈 줄이기

---

lib/utils/address_util.dart
lib/widgets/body/send_address/send_address_body.dart

- 비트코인 주소 표현 형식 수정(앞 10글자 + ... + 뒤 10글자) 
1. 어플 실행하여 테스트
1. 지갑 리스트 - 지갑 디테일 - 보내기 화면에서 '주소 ~ 붙여넣기' 버튼 확인
TC: 1BviRJRgcoqkN4Z115o7R1XgKo6QvzaJQp
#318

[318] 특정 주소 클립보드 복사 - 주소 스캔/붙여넣기 화면 에러

---

lib/providers/view_model/send/send_address_view_model.dart
test/view_model/send_address_view_model_test.dart

`send_address_view_model.dart` 수정
- bech32 대문자 입력되는 경우, 소문자로 변경하여 lib 검증 함수 호출 / 라이브러리 수정없이 동작하도록 소문자로 변경하여 sendInfoProvider에 저장
`send_address_view_model_test.dart` 추가
- regtest인 경우 코코넛 네트워크 안에서만 유효하므로, 기존 코드대로 m,n 주소 검증하지 않음
```
flutter pub run build_runner build --delete-conflicting-outputs
```
```
flutter test ./test/view_model/send_address_view_model_test.dart
```

bech32 주소 대문자 허용

---

lib/screens/wallet_detail/address_search_screen.dart

style(address_search_screen): 검색 결과 문구를 상단에 고정하도록 변경, 돋보기 아이콘 클릭 이벤트 제거
1. 어플 실행하여 테스트
1. 지갑 디테일 화면 - 상단에 지갑 이름 클릭 - 지갑 정보 화면에서 전체 주소 보기 클릭 - 주소 리스트 화면 우측 상단 돋보기 버튼 클릭 - 주소 검색 화면에서 테스트 진행
2. 초기 상태에서 상단 문구가 보이지 않아야 합니다. 
3. 결과가 있는 경우: 'xx' 검색 결과 주소 n개를 찾았어요 / 결과가 없는 경우: 'xx' 검색 결과 문구가 상단에 고정되어야 합니다. 
4. (추가 수정사항) 검색창 돋보기 아이콘 클릭시 ripple 효과 제거되었습니다.
<image src="https://github.com/user-attachments/assets/4ecfc0d0-a9a5-4005-b696-e4f7251ce542" width="250px" />
<image src="https://github.com/user-attachments/assets/bdc8da0b-7737-444d-b700-0b0177573ae8" width="250px" />
#321

[321] 주소 검색 화면 결과 문구 상단 고정

---

lib/providers/view_model/wallet_detail/address_list_view_model.dart

fix(address_list_view_model): 월렛 주소 인덱스가 0부터 나오도록 수정
어플 실행하여 테스트
1. 지갑 리스트 화면 지갑 클릭 - 지갑 디테일 화면 상단에 지갑 정보 클릭 - 전체 주소 보기 클릭 - 주소 인덱스가 정상적으로 나오는지 확인
#333

[333] 지갑 주소 인덱스가 1부터 나오는 현상

---

lib/repository/realm/transaction_repository.dart
lib/screens/send/broadcasting_complete_screen.dart

feat(broadcasting_complete_screen): 트랜잭션 전송 후 '메모 추가' 기능 추가
fix(transaction_repository): 메모 추가/업데이트 되도록 수정(오류 수정)
fix(transaction_repository): 지갑 디테일 - 거래 내역 트랜잭션 메모 확인할 수 있도록 수정(메모 쿼리 추가)
어플 실행하여 테스트
1. 지갑 디테일 화면 - 거래 디테일 화면 - 메모 수정 - 지갑 디테일 화면에서 '메모' 확인
2. 지갑 디테일 화면에서 보내기 버튼을 눌러서 전송 완료 화면까지 이동 - 메모 입력 X, 확인 클릭 - 지갑 디테일 화면에서 '메모' 안 나오는지 확인
3. 지갑 디테일 화면에서 보내기 버튼을 눌러서 전송 완료 화면까지 이동 - 메모 입력 O, 확인 클릭 - 지갑 디테일 화면에서 '메모' 확인
4. 기존에 추가된 메모는 다시 '지갑 디테일 화면'으로 진입시 제대로 보여지는지 확인
#300

[300] 트랜잭션 메모 기능

---

assets/i18n/kr.i18n.yaml
lib/providers/utxo_tag_provider.dart
lib/providers/view_model/wallet_detail/utxo_detail_view_model.dart
lib/providers/view_model/wallet_detail/utxo_list_view_model.dart
lib/providers/view_model/wallet_detail/utxo_tag_crud_view_model.dart
lib/repository/realm/utxo_repository.dart
lib/screens/common/tag_bottom_sheet.dart
lib/screens/common/tag_edit_bottom_sheet.dart
lib/screens/wallet_detail/utxo_detail_screen.dart
lib/screens/wallet_detail/utxo_list_screen.dart
lib/screens/wallet_detail/utxo_tag_crud_screen.dart
lib/widgets/header/utxo_list_header.dart
lib/widgets/header/utxo_list_sticky_header.dart
lib/widgets/header/utxo_tag_list_widget.dart
lib/widgets/textfield/custom_limit_text_field.dart
test/screens/bottomsheet/tag_bottom_sheet_screen_test.dart

- [feat] tag_edit_bottom_sheet에서 변경/추가/삭제 가능
- 적용 태그 변경: 태그 칩 탭
- 태그 삭제: utxo에 적용되지 않은 태그만 삭제 가능
- 변경: 태그 칩 롱 프레스
- [refactor] tag_edit_bottom_sheet.dart 추가: TagBottomSheet에서 추가/변경 상태 분리
- [fix/refactor] utxo list 화면 utxo tag 리스트 갱신 안되는 오류
코코넛 크루 요청 사항 https://discord.com/channels/1371632037663871066/1383966722834567309

UTXO 상세 화면에 태그 관리 기능 추가

---

lib/screens/send/unsigned_transaction_qr_screen.dart
lib/widgets/animated_qr/animated_qr_view.dart

Unsigned Transaction 화면의 QR 여백이 일치하지 않았던 현상을 해결했습니다.
모든 기기(볼트, 키스톤, 시드사이너, 제이드)로 테스트 한 결과,
QR에 담긴 정보량(density)과 QR 패딩이 스캔 성공 여부에 영향이 있음을 확인했습니다.
-> 해당 기기의 스캔 성공률이 높아지도록 패딩을 조정하는 것 보다는 density의 초기 설정값을 다르게 하는 것이 통일성이 있다고 생각했습니다.
QR의 패딩은 모든 기기에서 16으로 통일했습니다.
```dart
final screenWidth = MediaQuery.of(context).size.width;
final isNarrowScreen = screenWidth < 360;
switch (_walletImportSource) {
case WalletImportSource.coconutVault:
case WalletImportSource.keystone:
// 볼트와 키스톤은 스캔 성능이 우수하기 때문에 일반/좁은 화면 모두 _qrScanDensity: fast, padding: 16으로 설정
_qrScanDensity = QrScanDensity.fast;
break;
case WalletImportSource.seedSigner:
case WalletImportSource.extendedPublicKey:
// 시드사이너는 좁은 화면에서 _qrScanDensity slow가 안정적임
_qrScanDensity = isNarrowScreen ? QrScanDensity.slow : QrScanDensity.fast;
break;
case …
```

[358] Unsigned Transaction의 QR 여백 사이즈 조정

---

lib/providers/view_model/send/send_address_view_model.dart
lib/screens/send/send_address_screen.dart
lib/utils/address_util.dart
lib/widgets/body/send_address/send_address_amount_body_for_batch.dart
lib/widgets/card/address_and_amount_card.dart

- send_address_view_model.dart
- _parseBip21Address 추가
- validateAddress, loadDataFromClipboard, saveWalletIdAndRecipientAddress에서도 사용하도록 수정
- 블루월렛, 넌척에서 보여주는 주소 QR을 스캔
- 입력 정보 확인에서 주소가 일치하는지 확인

주소 스캔 시 BIP21 지원하도록 수정

---

assets/i18n/en.i18n.yaml
assets/i18n/kr.i18n.yaml
lib/screens/home/wallet_list_user_experience_survey_bottom_sheet.dart
lib/screens/review/negative_feedback_screen.dart
lib/screens/review/positive_feedback_screen.dart
lib/screens/wallet_detail/transaction_detail_screen.dart

transactionDetailScreen화면의 하드코딩되어 있던 '%d분 째', '%d시간 째', '%d일 째' 문구를 slang에 추가
- 방금 전     |    just now
- %d분 째   |   %d minutes ago
- %d시간 째   |   %d hours ago
- %d일 째   |   %d days ago
---
트랜잭션 실행 후 뜨는 리뷰요청 bottom sheet에 영문버전에서 개행되는 현상이 발생하여, fittedBox로 수정 후 전체 패딩 16 추가
---
1) 앱 언어를 영문으로 설정 후 트랜 잭션 실행
2) 이후 뜨는 리뷰 요청 화면에서 개행 없이 FittedBox가 적용되는지 확인 (negativeFeedbackScreen에서 'Please let us know if you have any inconvenience or suggestions!' 문구는 FittedBox로 적용 시 문구가 너무 작아지기 때문에 Please let us know**\n**if you ... 로 개행 적용
3) 트랜잭션 상세 화면으로 이동 후 시간 표시가 영문으로 나오는지 확인
#374

[374] 영문 UI 수정 사항

---

assets/i18n/en.i18n.yaml
assets/i18n/kr.i18n.yaml
lib/constants/shared_pref_keys.dart
lib/providers/preference_provider.dart
lib/screens/home/wallet_add_input_screen.dart
lib/screens/wallet_detail/address_list_screen.dart
lib/screens/wallet_detail/wallet_detail_receive_address_bottom_sheet.dart
lib/screens/wallet_detail/wallet_detail_screen.dart

- 입금 목록에서 툴팁을 '다시 보지 않기' 해도 잔돈 목록의 툴팁을 '다시 보지 않기'를 하지 않으면 잔돈 툴팁은 보임
---
- 화면 공간 차지 최소화
- offset이 0 ~ (ToolTip 높이 / 2) 구간에서 손을 뗴면 상단으로 이동, (ToolTip 높이 / 2) ~ ToolTip 높이 구간에서 손을 떼면 AddresList 0번째 인덱스로 이동
---
- '다시 보지 않기' 하면 앱 삭제 후 재설치 시점까지 보이지 않음
- PrefereceProvider ``` _isReceivingTooltipDisabled ```, ``` _isChangeTooltipDisabled ```
1) **한글** 모드에서 테스트 (영문 설정에서는 툴팁 노출하지 않음)
2) 지갑의 '전체 주소 보기' 화면에서 '입금' 툴팁과 '잔돈' 툴팁이 바뀐 형태로 표시되는지 확인합니다.
3) '다시 보지 않기' 클릭 후 화면 이동 후 복귀 또는 앱 재실행 시 더이상 툴팁이 보이지 않아야 합니다.
4) 지갑 상세 화면 -> [받기]버튼 -> '전체 주소 보기' (BottomSheet 형태) 에서도 동일하게 작동하는지 확인합니다.
#386

[386] 전체주소보기 툴팁 UI 변경/개선

---

lib/constants/shared_pref_keys.dart
lib/providers/preference_provider.dart
lib/providers/view_model/send/refactor/send_view_model.dart
lib/screens/send/refactor/send_screen.dart

- 보내기 화면 '수신자 추가하기 카드' 확인 여부에 따른 Bounce 애니메이션 처리
- PreferenceProvider '수신자 추가하기 카드' 확인 여부 변수 추가
어플 실행하여 테스트
1. (초기) 보내기 화면 진입시 Bounce 애니메이션 확인 
2. (수신자 추가하기 카드를 스크롤 하기 전) 보내기 화면 진입시 Bounce 애니메이션이 1회 처리됨.
3. (수신자 추가하기 카드를 스크롤 한 이후) 보내기 화면 진입시 Bounce 애니메이션이 처리되지 않음. 
#408

[408] 보내기 화면 진입 시 카드 흔들리는 애니메이션

---

lib/providers/view_model/home/wallet_add_input_view_model.dart
lib/providers/view_model/home/wallet_add_scanner_view_model.dart
lib/providers/wallet_provider.dart
lib/widgets/icon/wallet_item_icon.dart

- 확장공개키, 디스크립터를 통해 외부지갑 추가 시 즐겨찾기 목록, 지갑 순서 목록에도 추가
- WalletItemCard의 Icon Size 조정
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
1. RegTest에서 [지갑 추가] - [직접 입력] - 확장공개키 입력```vpub5ZdVSzwrt5MtucJVAJb3oKASCZLjYQeNkGmns66BpHhNhNYSP8yubjjhYAYSEZQQP7uiiGtQstg99NvKdqM7YBMBkRzEGTbS1sC4zWbdAgp```
2. 홈화면의 즐겨찾기 목록, 지갑 전체보기 화면에 잘 추가됐는지 확인
3. 이후 다른 지갑 추가해도 확장공개키로 추가한 지갑이 사라지지 않는지 확인(기존에는 사라졌었음)
4. 아이콘 사이즈 동일 여부 확인
5. 확장공개키로 추가한 지갑 삭제시 에러 발생 여부 확인(기존에는 에러 발생)
#415

[415] 써드파티로 지갑 추가시 발생하는 버그 수정

---

lib/providers/view_model/send/refactor/send_view_model.dart
lib/screens/home/wallet_home_screen.dart
lib/screens/send/refactor/select_wallet_bottom_sheet.dart
lib/screens/send/refactor/select_wallet_with_options_bottom_sheet.dart
lib/screens/send/refactor/send_screen.dart
lib/screens/wallet_detail/wallet_detail_receive_address_screen.dart
lib/utils/wallet_util.dart

feat(send_screen): 초기에 MFP 없는 지갑이 선택된 경우, Toast 메시지 출력
- MFP 없는 지갑의 경우 지갑 이름 - 표시
- 상단 앱바, MFP 월렛이 있는 경우에만 옵션 바텀시트를 출력하도록 처리
feat(select_with_options_bottom_sheet): MFP가 없는 지갑의 경우, 지갑 이름 - 표시, UTXO 관련 옵션 수정 불가하도록 처리
- 지갑선택 바텀시트에서 MFP가 있는 지갑만 보여주도록 처리
- MFP를 가진 지갑이 존재하지 않는 경우, 바텀시트 자체를 출력하지 않도록 처리
어플 실행하여 테스트
[확장공개키 1]
tpubDDt5xij8skd8vfu2ptUKEzCk5HKYuZpyTsJBRuq4WsKHPpmSfExeYm4A2RnpGqu51WVFNtcsVkSPdmX1ctC5am2sPMEvDBvb6xd216itFG6
[확장공개키 2]
vpub5Z6wrDZJQ78faJ3PYfYs7et7ep8d8uCXivpa3cdxw3joZrN2dfkYuP2xfCgFWscYcvQFAHoVDMcPKrmF7ekcrwQiKcn8qQtEBwuqoMSfJte
#418

[418] MFP 없는 지갑 보내기 안되도록 처리

---

lib/providers/preference_provider.dart
lib/providers/view_model/home/wallet_add_input_view_model.dart
lib/providers/view_model/home/wallet_add_scanner_view_model.dart
lib/providers/wallet_provider.dart
lib/screens/home/wallet_add_input_screen.dart
lib/screens/home/wallet_add_scanner_screen.dart
lib/screens/home/wallet_home_screen.dart
lib/screens/settings/fake_balance_bottom_sheet.dart
lib/screens/settings/settings_screen.dart
lib/widgets/card/wallet_item_card.dart

[기존]
- 잔액 숨겨진 상태에서 보기 상태로 전환 시 가짜잔액이 활성화 상태더라도 자동으로 비활성화 상태가 됩니다.
- 이로 인해 홈화면에서 가짜 잔액 표시 상태에서 숨기기 -> 보기 전환시 실제 잔액으로 표기되는 현상이 있습니다.
- 이 현상이 일어나는 이유는 설정화면에서 잔액 숨기기 토글 버튼을 활성화->비활성화 상태로 전환 시 자동으로 가짜 잔액도 활성화 -> 비활성화 하기 위해 구현된 로직이 원인이었습니다.
[변경]
- 가짜 잔액 로직과 잔액 숨기기 로직을 분리하였습니다.
- 다음과 같이 동작합니다.
- ex: 가짜 잔액 1BTC로 설정
- 잔액 숨기기 시 '잔액 보기'로 전환
- 잔액 숨기기 해제 시 1BTC로 표시
- ex: 가짜 잔액 설정 안함
- 잔액 숨기기 시 '잔액 보기'로 전환
- 잔액 숨기기 해제 시 실제 잔액으로 표시
#427

[427] 잔액 숨김/보이기 로직과 가짜잔액 로직 분리

---

lib/providers/view_model/home/wallet_list_view_model.dart
lib/providers/view_model/send/refactor/send_view_model.dart
lib/screens/home/wallet_list_screen.dart
lib/screens/send/refactor/send_screen.dart
lib/utils/address_util.dart

1. 블루월렛을 사용하여 amount 지정하여 받을 주소 정보 생성
-  받기 - 금액 명시 후 받기 - 금액 입력 - [생성하기]
2. 코코넛 월렛 send 화면에서 주소 입력란 우측 - 스캔 아이콘 클릭하여 bip21 QR 스캔
3. 블루월렛에서 명시한 금액이 코코넛 월렛 보내기 화면 보낼 금액에 추가됨.
4. (추가) 주소 qr 스캔 시 prefix 'bitcoin:' 제거되는지 확인
#413

[413] bip21 data에 amount가 있는 경우 보내는 정보로 사용

---

lib/providers/view_model/home/wallet_add_scanner_view_model.dart
lib/screens/send/signed_psbt_scanner_screen.dart
lib/services/wallet_add_service.dart
lib/widgets/animated_qr/scan_data_handler/bc_ur_qr_scan_data_handler.dart
lib/widgets/animated_qr/scan_data_handler/composed_scan_data_handler.dart
pubspec.yaml

1. 지갑 추가 > 시드사이너 선택 > descriptor QR 뿐만 아니라 bc-ur animated QR도 인식 가능하도록 수정
(composedScanDataHandler 생성)
지갑 추가 > 시드사이너 선택
1. 기존 시드사이너의 descriptor QR로 지갑 추가 가능
2. 현재 v0.8.6이상이 설치된 시드사이너가 없으므로 키스톤이나 Jade의 지갑 내보내기 QR을 스캔했을 때도 지갑 추가 가능

[471] seedsigner wallet add - bc-ur 지원
