noncelab/coconut_wallet

ios/Runner/AppDelegate.swift, lib/screens/send/send_address_screen.dart
=> 붙여넣기 버튼 수정

lib/model/manager/realm/model/coconut_wallet_data.dart, lib/model/manager/wallet_data_manager_cryptography.dart, lib/screens/send/send_address_screen.dart, lib/screens/signed_psbt_scanner_screen.dart, test/screens/bottomsheet/tag_bottom_sheet_screen_test.dart
#52
- 주소 복사 스캔 실패 토스트 위젯 변경
- 서명 트랜잭션 읽기 스캔 실패 alert 중복 실행 수정
=> 보내기 스캐너 수정 사항 반영

lib/model/manager/realm/model/coconut_wallet_data.dart, lib/model/manager/realm/model/coconut_wallet_data.realm.dart, lib/model/manager/wallet_data_manager.dart, lib/model/manager/wallet_data_manager_cryptography.dart, lib/model/utxo.dart, lib/providers/app_state_model.dart, lib/screens/send/broadcasting_screen.dart, lib/screens/send/send_address_screen.dart, lib/screens/send/send_fee_selection_screen.dart, lib/screens/send/send_utxo_selection_screen.dart, lib/screens/utxo_detail_screen.dart, lib/screens/wallet_detail_screen.dart, lib/screens/wallet_multisig_screen.dart, lib/screens/wallet_setting_screen.dart, lib/utils/utxo_util.dart
=> UTXO 고르기 플로우

lib/providers/view_model/wallet_detail/address_list_view_model.dart, lib/screens/wallet_detail/address_list_screen.dart, lib/widgets/card/address_list_address_item_card.dart
예상 작업시간: 1h [2024-01-17 18:30]
최종 작업시간: 1.5h
=> [12-913] [VM] address_list_screen

lib/providers/view_model/onboarding/start_view_model.dart, lib/screens/onboarding/start_screen.dart
예상 작업시간: 1h [2024-01-17 16:30]
최종 작업시간: 1h
=> [12-912] [VM] start_screen

lib/app.dart, lib/providers/view_model/send/send_amount_view_model.dart, lib/providers/view_model/send/send_fee_selection_view_model.dart, lib/screens/send/fee_selection_screen.dart, lib/screens/send/send_amount_screen.dart, lib/screens/send/send_fee_selection_screen.dart, lib/widgets/card/send_fee_selection_item_card.dart
예상 작업시간: 0.5 [2024-01-22 17:30]
- send_amount_screen에서 viewModel분리 작업
- _input, _errorIndex, _enableNextButton, _onKeyTap(), '최대' 버튼 실행함수
최종 작업시간: 0.5h
=> [12-932] [VM] send_amount_screen

lib/providers/view_model/wallet_detail/wallet_detail_view_model.dart, lib/screens/wallet_detail/wallet_detail_screen.dart, lib/widgets/header/wallet_detail_sticky_header.dart, lib/widgets/selector/wallet_detail_tab.dart
예상 작업시간: 2h [2024-01-22 13:20]
- walletDetailViewModel에서 Tag기능 외 다른 기능들의 AppStateModel 의존성을 제거했습니다.
- Tag관련 Provider 완료 후 ViewModel에서 AppStateModel 완전 제거가 필요합니다.
최종 작업시간: 3h 
#68
=> [12-923] [VM] wallet_detail_screen

lib/providers/view_model/send/broadcasting_view_model.dart, lib/providers/view_model/send/send_confirm_view_model.dart, lib/screens/send/broadcasting_screen.dart, lib/screens/send/send_confirm_screen.dart, lib/screens/send/send_fee_selection_screen.dart
- sort members
- setTxInfo 메서드 viewModel로 이동
Co-Authored-By: EllaLim <73803777+Ella-noncelab@users.noreply.github.com>
#68
=> [12-925] [VM] broadcasting_screen

lib/app.dart, lib/providers/view_model/wallet_detail/wallet_multisig_info_view_model.dart, lib/providers/view_model/wallet_detail/wallet_singlesig_info_view_model.dart, lib/screens/home/wallet_list_screen.dart, lib/screens/wallet_detail/wallet_multisig_info_screen.dart, lib/screens/wallet_detail/wallet_singlesig_info_screen.dart, lib/widgets/card/multisig_signer_card.dart, lib/widgets/overlays/user_experience_survey_bottom_sheet.dart
예상 작업시간: 5h [2024-01-24 10:20]
최종 작업시간: 2h [2024-01-24 12:00]
=> [12-909] wallet_*_info_screen

lib/app.dart, lib/providers/app_state_model.dart, lib/providers/view_model/home/wallet_list_view_model.dart, lib/providers/wallet_provider.dart, lib/screens/home/wallet_list_screen.dart, lib/screens/send/send_address_screen.dart, lib/widgets/header/wallet_detail_header.dart
- app.dart에 있던 wallet_list_screen_view_model 생성을 화면으로 가져옴
=> [12-954] 네트워크 동기화 완료/에러 시 진동 효과 복원

lib/providers/app_sub_state_model.dart, lib/providers/auth_provider.dart, lib/providers/preference_provider.dart, lib/providers/view_model/onboarding/start_view_model.dart, lib/providers/view_model/send/broadcasting_view_model.dart, lib/providers/view_model/send/send_confirm_view_model.dart, lib/providers/view_model/send/send_utxo_selection_view_model.dart, lib/providers/view_model/wallet_detail/wallet_detail_view_model.dart, lib/providers/visibility_provider.dart, lib/providers/wallet_provider.dart, lib/repository/shared_preference/shared_prefs_repository.dart, lib/screens/send/broadcasting_complete_screen.dart, lib/screens/send/broadcasting_screen.dart, lib/screens/send/send_utxo_selection_screen.dart, lib/services/app_review_service.dart, test/services/shared_prefs_service_test.dart
=> [13-957] Fix/send utxo selection

lib/screens/send/broadcasting_screen.dart, lib/screens/wallet_detail/transaction_detail_screen.dart, lib/screens/wallet_detail/utxo_detail_screen.dart, lib/screens/wallet_detail/wallet_detail_screen.dart
=> [13-971/972] minor ui 버그

assets/i18n/kr.i18n.yaml, lib/localization/strings.g.dart, lib/localization/strings_kr.g.dart, lib/model/error/app_error.dart, lib/utils/alert_util.dart, pubspec.yaml, slang.yaml
예상 작업시간: 4h [2024-02-03 16:12]
related to Issue #98
=> [13-958] i18n 적용

lib/app.dart, lib/providers/view_model/send/send_fee_selection_view_model.dart, lib/screens/send/broadcasting_complete_screen.dart, lib/screens/send/broadcasting_screen.dart
=> [13-981] 보내기 완료 화면의 ‘트랜잭션 보기’ 버튼 제거하기

lib/providers/view_model/wallet_detail/transaction_detail_view_model.dart, lib/providers/view_model/wallet_detail/utxo_detail_view_model.dart, lib/repository/realm/converter/transaction.dart, lib/repository/realm/wallet_data_manager.dart, lib/screens/wallet_detail/transaction_detail_screen.dart, lib/screens/wallet_detail/utxo_detail_screen.dart, lib/widgets/body/wallet_detail_body.dart, lib/widgets/card/transaction_item_card.dart, lib/widgets/card/utxo_item_card.dart
- 홀수 인덱스 거래 내역 안보이는 버그
- uxto 같은 것이 2개씩 보이는 버그
- 목록 아이템 borderWidth 0으로 변경, 아이템 간 간격 설정
related to Issue #97
=> [13-985/973] tx, utxo 목록 오류

lib/app_guard.dart, lib/constants/external_links.dart, lib/screens/home/wallet_list_screen.dart, lib/widgets/button/shrink_animation_button.dart, pubspec.yaml
- 앱 진입시 뜨는 CupertinoActivityIndicator Size, animation 조정
- 네트워크 미연결시 상단에 알림바 표시 + 애니메이션 진행
- Wallet item card, 싱글 시그일 때 다른 카드들과 달리 width가 짧은 현상 수정
- AppGuard에서 수행하는 Network 토스트 임시 주석 처리
- wallet-list에서 네트워크 미연결시 뜨는 상단 알림바와 겹치기 때문
=> [13-1006] wallet-list-ui 수정사항

lib/model/wallet/wallet_list_item_base.dart, lib/providers/view_model/send/send_confirm_view_model.dart, lib/providers/view_model/send/send_fee_selection_view_model.dart, lib/providers/view_model/send/send_utxo_selection_view_model.dart, lib/screens/send/send_fee_selection_screen.dart, lib/services/model/response/block_header.dart
- walletFeature 대신 변경된 함수로 사용하도록 변경
- coconut_lib 최신 버전 변경사항 대응 (트랜잭션 생성시 파라미터 전달 방법 변경, hex디코드 함수 변경)
=> [14-1029] estimateFee API 적용

lib/providers/node_provider/transaction/transaction_fetcher.dart, lib/providers/node_provider/utxo_manager.dart, lib/providers/view_model/send/send_utxo_selection_view_model.dart, lib/screens/send/send_utxo_selection_screen.dart, lib/services/electrum_service.dart, lib/utils/transaction_util.dart, lib/widgets/card/selectable_utxo_item_card.dart
1. utxo-selection 화면에서 금액이 같은 utxo의 경우 최신순으로 정렬되도록 수정
2. optimal utxo 선택 시 confirmed utxo만 사용 가능하도록 수정
=> [14-1054] Fix/send optimal utxo

lib/providers/view_model/send/send_utxo_selection_view_model.dart, lib/screens/wallet_detail/utxo_list_screen.dart, lib/widgets/custom_loading_overlay.dart
utxo리스트 화면 - 마지막 아이템 표시 중 out of range 에러 발생현상 해결, CustomLoadingOverlay 배경색 어두운 계열로 변경
=> [14-1066,1067,1068] (Closed된 브랜치 복구) utxo리스트 화면 에러, CustomLoadingOverlay 수정 건

lib/repository/realm/converter/transaction.dart, lib/repository/realm/model/coconut_wallet_model.dart, lib/repository/realm/model/coconut_wallet_model.realm.dart, lib/repository/realm/transaction_repository.dart, test/providers/node_provider/transaction_manager_test.dart, test/providers/node_provider/transaction_manager_test.mocks.dart
- RBF 내역 중복 표기 오류 수정
- RBF 내역 중 특정 상황에서 수수료율순으로 표기 안되는 오류 수정
=> [14-1058] RBF 내역 중복/순서 표기 오류 수정

lib/providers/node_provider/transaction/models/rbf_info.dart, lib/providers/node_provider/transaction/rbf_handler.dart, lib/providers/node_provider/transaction/transaction_fetcher.dart, lib/providers/node_provider/utxo_manager.dart, lib/services/electrum_service.dart
- RBF 트랜잭션 수신할 경우 원래 존재하던 Incoming Utxo가 대체되지 않고 새로 추가되기만 하는 오류 수정
=> [14-1092] RBF 받는 지갑 관점에서 UTXO 삭제 안되는 오류 수정

lib/providers/view_model/send/send_confirm_view_model.dart, lib/screens/send/broadcasting_screen.dart, lib/screens/send/fee_selection_screen.dart, lib/screens/send/send_confirm_screen.dart, lib/screens/send/send_fee_selection_screen.dart, lib/screens/send/send_utxo_selection_screen.dart, lib/screens/wallet_detail/transaction_detail_screen.dart, lib/screens/wallet_detail/utxo_detail_screen.dart, lib/screens/wallet_detail/wallet_detail_screen.dart, lib/widgets/card/send_fee_selection_item_card.dart, lib/widgets/card/send_utxo_sticky_header.dart, lib/widgets/contents/fiat_price.dart, lib/widgets/header/utxo_list_header.dart
- 시세 위젯 생성: FiatPrice
- 시세 보여줘야하는 화면에서 FiatPrice 사용
=> [14-1038] 시세 렌더링 위젯 생성

lib/screens/send/send_address_screen.dart, lib/screens/send/send_amount_screen.dart, lib/screens/wallet_detail/transaction_fee_bumping_screen.dart, lib/widgets/body/send_address/send_address_amount_body_for_batch.dart, lib/widgets/button/single_bottom_button.dart, lib/widgets/card/address_and_amount_card.dart
- transaction_fee_bumping_screen과 동일하게 하단 버튼 높이 조정
- 하단 버튼 바깥 영역 반투명 백그라운드 배치(버튼 색상이 동일하기 때문에 구분이 안돼서 추가했습니다.)
- SafeArea Bottom값 false로 변경
추가) [feat/single-bottom-button]
SingleBottomButton 위젯으로 분리했습니다.
- 반투명 백그라운드, CoconutButton을 포함한 위젯입니다.
=> [14-1083] batch-tx 부분 ui 수정

lib/providers/node_provider/isolate/isolate_manager.dart, lib/providers/node_provider/transaction/cpfp_handler.dart, lib/providers/node_provider/transaction/transaction_fetcher.dart, lib/providers/node_provider/utxo_manager.dart, lib/providers/view_model/wallet_detail/fee_bumping_view_model.dart, lib/providers/view_model/wallet_detail/transaction_detail_view_model.dart, lib/repository/realm/utxo_repository.dart, lib/screens/wallet_detail/utxo_list_screen.dart, test/mock/transaction_mock.dart, test/providers/node_provider/transaction_manager_test.dart
- 내 Utxo와 언컨펌 입력을 비교하여 Cpfp 확인하는 로직 개선
- Isolate Realm 초기화 로직 추가
- 기타 테스트코드 컴파일 오류 수정
=> [14-1098] 다른 지갑의 CPFP가 내 지갑의 CPFP로 인식되는 오류

lib/widgets/body/send_address/send_address_amount_body_for_batch.dart, lib/widgets/card/address_and_amount_card.dart
'받는 사람 추가하기' 클릭시 scrollToBottom, 
TextField클릭시 해당 위치로 scroll, 
스캔 완료시 수량입력필드로 Focus 넘어가는 기능 구현
CDS 재설치 필요합니다.
#116
=> [14-1097] Batch 트랜잭션 화면 AutoFocus 기능

lib/app.dart, lib/providers/node_provider/state_manager.dart, lib/providers/wallet_provider.dart, lib/repository/realm/utxo_repository.dart, lib/repository/realm/wallet_repository.dart, lib/screens/wallet_detail/wallet_info_screen.dart, lib/widgets/custom_loading_overlay.dart
(As-is) 동기화 동안 지갑을 삭제하지 못하도록 막고 있음.
(Problem) 지갑을 삭제하려면 사용자는 동기화가 끝날때까지 기다려야 함.
(To-be) 사용자는 동기화 중에도 지갑을 삭제할 수 있고, 월렛은 사용하던 프로세스를 안전하게 정리함.
=> 동기화 중 지갑 삭제하기

lib/providers/view_model/wallet_detail/transaction_detail_view_model.dart, lib/screens/wallet_detail/transaction_detail_screen.dart
상황:  rbf 직후 transaction_detail 화면으로 들어왔을 때 rbf history 정렬 되지 않는 현상이 있었습니다.
=> fix(history-list): rbf history 정렬 되지 않는 버그 수정

lib/constants/shared_pref_keys.dart, lib/providers/auth_provider.dart, lib/providers/preference_provider.dart, lib/providers/view_model/onboarding/start_view_model.dart, lib/repository/shared_preference/shared_prefs_repository.dart, lib/services/app_review_service.dart, test/services/shared_prefs_service_test.dart
- sharedPrefKeys의 상수로 대체
- 사용 안하는 key 제거
=> refactor(sharedPrefKeys): sharedPrefsRepository 내부의 key 제거

lib/model/utxo/utxo_state.dart, lib/providers/node_provider/utxo_manager.dart, lib/screens/wallet_detail/utxo_list_screen.dart, lib/widgets/card/utxo_item_card.dart, lib/widgets/header/utxo_list_header.dart, lib/widgets/header/wallet_detail_header.dart, test/model/utxo/sort_utxo_list_test.dart
- `fix`
- _isListChanged 추가: utxo 변경이 있을 때만 리스트를 업데이트함.
- _handleUtxoListChange 변경: 비동기 함수로 변경, 애니메이션 제어 후 utxo 목록이 업데이트 됨
- model/utxo/utxo_state.dart `sortUtxo` 변경: incoming/outgoing utxo 우선 정렬
- `refactor`: UtxoList 매개변수 수정 (`UtxoListScreen` -> `int`)
- `feat`: iOS / 노치 터치시 최상단으로 스크롤 기능 추가
#166
=> [166] utxo가 사라질 때 렌더링 에러

lib/providers/node_provider/isolate/isolate_enum.dart, lib/providers/node_provider/isolate/isolate_handler.dart, lib/providers/node_provider/isolate/isolate_state_manager.dart, lib/providers/node_provider/state_manager.dart, lib/providers/node_provider/state_manager_interface.dart, lib/providers/node_provider/subscription/script_callback_manager.dart, lib/providers/node_provider/subscription/script_event_handler.dart, lib/providers/node_provider/subscription/script_handler_util.dart, lib/providers/node_provider/transaction/transaction_fetcher.dart, test/providers/node_provider/transaction_manager_test.dart
- 지갑 중 어느 항목이라도 싱크중일 경우 `connectionState`가 완료로 변경되지 않도록 수정
- 지갑 중 어느 항목이라도 싱크 완료할 경우 나머지 상태들도 확인 후 모두 완료되었다면 `connectionState`도 완료로 변경
1. 지갑 A, B 아무거나 빠르게 2개 추가 (내역이 많은 것을 먼저 추가하여 동기화 시간이 길어지게 유도하고 끝나기 전에 새로운 지갑을 추가해야 함.)
2. A → B 혹은 B → A 트랜잭션 전송
3. state 로그 프린트 확인, 각 화면별 동기화 후 로딩 바 사라지는지 확인
- 변경사항이 여러 지갑과 여러 핸들러가 동시다발적으로 발생 시 간헐적으로 발생함.
- Balance, Transaction, Utxo 순으로 업데이트를 하도록 되어있음.
- 특별히 사용자에게 불편함을 주는 요소는 없는 것으로 확인되어 더 이상 작업하지 않음.
<table border="1">
<caption>연결 상태: 🔄 동기화 중</caption>
<thead>
<tr>
<th>지갑 ID</th>
<th>잔액</th>
<th>거래</th>
<th>UTXO</th>
</tr>
</thead>
<tbody>
<tr>
<td>2</td>
<td>✅</td>
<td>🔄</td>
<td>✅</td>
</tr>
<tr>
<td>1</td>
<td>✅</td>
<td>✅</td>
<td>✅</td>
</tr>
</tbody>
</table>
<table border="1">
<caption>연결 상태: ✅ 대기 중</caption>
<thead>
<tr>
<th>지갑 ID</th> …
=> [162] NodeProviderState 변경 오류 수정

lib/screens/home/wallet_list_screen.dart, lib/widgets/label_testnet.dart
- 홈화면 테스트넷 라벨 추가(wallet_list_screen)
1. 앱을 실행하여 테스트넷 라벨이 표시되는지 확인(regtest)
#229
=> [229] 월렛 홈화면 상단 '테스트넷' 라벨 추가

lib/screens/home/wallet_list_screen.dart
=> [UI] 지갑 추가 옵션 화면 - 닫기 버튼 터치 영역 수정

lib/screens/settings/realm_debug_screen.dart, lib/screens/settings/settings_screen.dart
- 디버거 화면 구현(아래 이미지 참고)
- 홈화면 ... - 설정 - Realm 데이터베이스 디버거 - 맨 위 테이블 선택 - 쿼리 입력 - 쿼리 실행버튼 클릭 - 원하는 데이터 확인
- #260
=> [#260] Realm 뷰어 화면 개발

lib/providers/view_model/wallet_detail/utxo_list_view_model.dart, lib/widgets/dropdown/utxo_filter_dropdown.dart
- 적용 화면: utxo_list_screen.dart
- 기존: 최신순, 오래된 순, 큰 금액순, 작은 금액순
- 변경: 큰 금액순, 작은 금액순, 최신순, 오래된 순
=> fix(utxo-order): 큰 금액순을 기본값으로 변경

assets/i18n/kr.i18n.yaml, lib/screens/send/broadcasting_screen.dart
* 버튼 FixedBottomButton으로 변경
* 버튼 이름 '보내기'로 적용
=> [UI] 최종 확인 화면 버튼 변경

lib/screens/send/refactor/send_screen.dart
- Discord Max님 버그 리포트
- Platform: Android
- 문제 현상: amount, fee rate 입력 포커스 후, 시스템 백버튼을 눌러 키보드를 닫았을 때, 키보드 상단 툴바가 남아있음.
- 해결: 키보드 높이를 감지하여, 키보드가 내려가면 amount, fee rate 포커스도 해제하도록 수정
=> [FIX] 안드로이드 백버튼 클릭 시 키보드 위 요소가 남아있음

assets/i18n/en.i18n.yaml, assets/i18n/kr.i18n.yaml, lib/enums/fiat_enums.dart, lib/providers/price_provider.dart, lib/screens/settings/fiat_bottom_sheet.dart, lib/screens/settings/settings_screen.dart, lib/services/web_socket_service.dart
https://discord.com/channels/1371632037663871066/1403997256096419892
1. 설정 - 단위 - 법정화폐 - JPY로 변경
2. 설정 - 단위 - 법정화폐 JPY로 표시됨
3. 홈, wallet_detail, utxo_list 모두 JPY로 표시됨
4. 다른 법정화폐로 변경시 위 2. 3. 화면에 모두 반영됨
=> [Feat] JPY 시세 지원

lib/providers/view_model/home/wallet_list_view_model.dart, lib/screens/home/wallet_list_screen.dart
=> feat(fiat-price): wallet list 화면 Fiat Price 표시

lib/constants/shared_pref_keys.dart, lib/providers/preference_provider.dart, lib/providers/view_model/send/refactor/utxo_selection_view_model.dart, lib/providers/view_model/wallet_detail/utxo_list_view_model.dart, lib/screens/send/refactor/utxo_selection_screen.dart, lib/screens/wallet_detail/utxo_list_screen.dart
- 마지막으로 선택한 utxo 정렬 유지 구현
<table>
<tr>
<td>
</td>
</tr>
</table>
#465
=> [465] 마지막으로 선택한 utxo 정렬 유지 구현
